branches:
    only:
        - release
dist: focal
sudo: required

jobs:
    include:
        - language : node_js
          node_js : 10
          before_script:
            - sudo apt-get update -qq
            - sudo apt-get install debhelper npm
          script : 
            - cd hamonize-agent/
            - sudo dpkg-buildpackage -T clean
            - sudo dpkg-buildpackage -b -us -uc -ui
        - language : cpp
          before_script:
            - git submodule init
            - git submodule update
            - sudo apt-get update -qq
            - sudo apt-get install g++ make cmake qtbase5-dev qtbase5-dev-tools qttools5-dev qttools5-dev-tools libqca-qt5-2-plugins xorg-dev libxtst-dev libjpeg-dev zlib1g-dev libssl-dev libpam0g-dev libprocps-dev liblzo2-dev libqca-qt5-2-dev libldap2-dev libsasl2-dev fakeroot
          script : 
            - cd hamonize-admin/ && mkdir build && cd build
            - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
            - fakeroot make package
            - mv *.deb ../../ && cd ..
before_deploy:
    - git config --local user.name "Hamonikr"
    - git config --local user.email "hamonikr@gmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag ${TRAVIS_TAG}
deploy:
    provider: releases
    api_key: 
        secure: "eqgvh+Dez4pF3akrzlKg4HX/JLumG2tGYm7KSGvz2oH6+vw3RjZG9GpSjplCk8PwvR3D8Zn9zND7+zbeINVWPkPozPiTDfH84L04Gb4tr72GJ5PqEt8B0oK7zg//t37MqnFEKzvvr/J6jM1jLNJ7SiooDjSy0c2a/bxxGA88BLxUffzcDC3/c5Eie99kbpLYoNhoflnYl5P3yBzW4nCBT2AsIGkq4ErJOkG/uJxdluHgS/qCaZSTGTRV69jnBj2/547B4/g3qNpj955VgIA9ei+XkLQk1shlc0h9t8NU4kmea9cIqFRBEKky2oq7MkulZQKWGQME0FTUfT/6OPYW9kvP/rQmuZc/4y+1flb2BE1IUDQBZUxLdktCuA9RO3ZkXxNObWXhtKiH0Zv66p/Xsa8BD2w5T2fYoId4LqtmyUDLsGAruHDlnxtcrnCiaoqhblt83vXiCY/yxFj8Ti7XXUKOW6/sBzTOz6QYIJTGKClF9YePu7BM5gei/A+rQaGvoA1kTUEqsijpA9YE6rIaYFeBULfHAk+kHyMmEmc882/+p4K4d3tLHxOelTE1gJ78id3jQHIwVc9SlXqQFNWXDheWH+7grBoJU0nd8uT5uBDhcTcpNGME7Igi0GyBZNHwqnHvONJLf+NSN9wX1msvgQKuSW3v4MWnJRclLpxoF5k="
    file_glob: true
    file: ../*.deb
    skip_cleanup: true
    draft: true
    on:
        branch: release

